apiVersion: apps/v1
kind: Deployment
metadata:
 name: docker-k8s-demo-deployment
 labels:
  app: docker-k8s-demo
spec:
  replicas: 1
  selector:
   matchLabels:
     app: deocker-k8s-demo
   spec: 
     containers:
     - name: deocker-k8s-demo
       image: Sijy28/docker-demo
       ports:
       - containerPort: 8086